// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVHMKTsH-7S5sSGJdXjb578juJQ5rQjQ',
    appId: '1:313171258283:web:01607c3297de65d20a80ee',
    messagingSenderId: '313171258283',
    projectId: 'todo-bibek',
    authDomain: 'todo-bibek.firebaseapp.com',
    storageBucket: 'todo-bibek.firebasestorage.app',
    measurementId: 'G-ZZ20ENM06B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXa8sgBjRDFXRQ2DASrJa1MDM7NqVCQDk',
    appId: '1:313171258283:android:ee1fe7f5bedf8f640a80ee',
    messagingSenderId: '313171258283',
    projectId: 'todo-bibek',
    storageBucket: 'todo-bibek.firebasestorage.app',
  );
}
